apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application-deployment
spec:
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
      - name: my-application
        image: serdardevops/my-application
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>
apiVersion: v1
kind: Service
metadata:
  name: my-application-deployment-service
spec:
  selector:
    app: my-application
  ports:
  - port: 8081
    targetPort: 8081
